(add-to-list 'load-path "~/emacs")

(load-file "~/emacs/conf/git.el")
(load-file "~/emacs/conf/theme.el")
(load-file "~/emacs/conf/global.el")
(load-file "~/emacs/conf/c-linux.el")
(load-file "~/emacs/conf/key.el")
(load-file "~/emacs/conf/gdb.el")
(load-file "~/emacs/conf/gtags.el")
(load-file "~/emacs/conf/cscope.el")
(load-file "~/emacs/conf/vline.el")
(load-file "~/emacs/conf/hilight.el")
(load-file "~/emacs/conf/col80.el")
